[package]
name = "zed_metal"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lib]
path = "src/metal.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = { workspace = true }
