id = "metal"
name = "metal-analyzer"
version = "0.1.4"
schema_version = 1
description = "metal-analyzer for Metal with enhanced syntax highlighting and fast navigation"
authors = ["Eugene Bokhan <eugenebokhan@icloud.com>"]
repository = "https://github.com/computer-graphics-tools/metal-analyzer"
icon_path = "../../editors/code/icon.png"

[language_servers.metal-analyzer]
name = "metal-analyzer"
languages = ["Metal"]

[grammars.cpp]
repository = "https://github.com/tree-sitter/tree-sitter-cpp"
commit = "12bd6f7e96080d2e70ec51d4068f2f66120dde35"
